theme = "adwaita-dark"
 
[editor]
bufferline = "always"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
# insert = "bar"

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
